spring:
  profiles:
    active: dev # 支持dev开发环境

  application:
    name: spring-ai3

  data:
    redis:
      host: ${lhr.redis.host}
      port: ${lhr.redis.port}
      password: ${lhr.redis.password}
      client-type: jedis

  ai:
    chat:
      memory:
        redis:
          host: ${lhr.redis.host}
          port: ${lhr.redis.port}
          initialize-schema: true
          metadata-fields:
            - name: role
              type: tag
            - name: messageType
              type: tag
    vectorstore:
      type: redis
      redis:
        initialize-schema: true

    openai:
      api-key: ${lhr.ai.openai.api-key}
      base-url: ${lhr.ai.openai.base-url}
      chat:
        model: ${lhr.ai.openai.chat.model}

      embedding:
        model: ${lhr.ai.openai.embedding.model}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${lhr.mysql.url}
    username: ${lhr.mysql.username}
    password: ${lhr.mysql.password}

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 40MB

# 日志配置
logging:
  level:
    org.springframework.ai: debug
    com.knowflow.springai: debug
